import Head from "next/head";

export default function Contribute() {
  return (
    <div>
      <Head>
        <title>Contribute | ResourceHub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Contribute</div>
    </div>
  );
}
