import Head from "next/head";
import Feed from "../components/explore/Feed";
import Header from "../components/explore/Header";
import Sidebar from "../components/explore/Sidebar";
import ThemeToggle from "../components/ThemeToggle";
import { useState } from "react";
import { PrismaClient } from "@prisma/client";
import { getSession } from "next-auth/react";

export default function Explore({ resources }) {
  console.log(resources);
  return (
    <div>
      <Head>
        <title>Explore | ResourceHub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Sidebar />

      <main className="w-full h-full bg-white dark:bg-black">
        <Feed resources={resources} />
        <ThemeToggle />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const prisma = new PrismaClient();
  if (!context.query.category) {
    const response = await prisma.resource.findMany({
      include: {
        uploader: true,
      },
    });

    // Pass the data to the Home page
    return {
      props: {
        resources: JSON.parse(JSON.stringify(response)),
      },
    };
  } else {
    const category = context.query.category;
    if (category == "blogs") {
      const response = await prisma.resource.findMany({
        include: {
          uploader: true,
        },
        where: {
          resourceCategory: {
            equals: "Blog",
          },
        },
      });

      // Pass the data to the Home page
      return {
        props: {
          resources: JSON.parse(JSON.stringify(response)),
        },
      };
    }
  }
}
