import Head from "next/head";
import ThemeToggle from "../components/ThemeToggle";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-blue-200 dark:bg-blue-900">
        <h1>Resource Hub</h1>
        <ThemeToggle />
      </main>
    </div>
  );
}
